apiVersion: apps/v1
kind: Deployment

metadata:
  name: klokkinn-frontend
  namespace: klokkinn

spec:
  replicas: 1
  selector:
    matchLabels:
      app: klokkinn-frontend
  template:
    metadata:
      labels:
        app: klokkinn-frontend
    spec:
      containers:
        - name: klokkinn-frontend
          image: ghcr.io/klokkinn/klokkinn-frontend:0.0.2
          env:
            - name: VITE_BASE_URL
              value: https://klokkinn.no
            - name: VITE_GATEKEEPER_URL
              value: https://gtk.klokkinn.no
            - name: VITE_TIME_SERVICE_URL
              value: https://gtk.klokkinn.no/api/time
